image:
- Visual Studio 2017
- Ubuntu

version: 0.1.0.{build}

# Only clone the current branch and no history
clone_depth: 1

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

nuget:
  # Do not publish NuGet packages for pull requests
  disable_publish_on_pr: true

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOCKER_PASS:
    secure: 7xusxxMFy9iURl0Ktuzri5XyT3/NDKlsU3kkfJ+Sq90=

branches:
  only:
    - master

skip_commits:
  files:
    - README.md

init:
  - git config --global core.autocrlf false

build_script:
  - ps: .\build.ps1
  - ps: .\build-docker.ps1

test_script:
  - dotnet build ./test/ServiceHost.Tests/ServiceHost.Tests.csproj --configuration Release
  - dotnet test ./test/ServiceHost.Tests/ServiceHost.Tests.csproj --configuration Release --no-build

deploy_script:
- ps: .\deploy-docker.ps1