name: Publish to GitHub Packagesp

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with docker
      run: docker build . -t "apiserver"
    - name: Tag with docker
      run: docker tag apiserver docker.pkg.github.com/DotNetRu/server/apiserver
    - name: Push with docker
      run: docker push docker.pkg.github.com/DotNetRu/server/apiserver
